using UnityEngine;
using UnityEditor;
using UnityEngine.Rendering;

public class ShaderVariantCollector
{
    [MenuItem("Shader/Collect Variants")]
    static void CollectShaderVariants()
    {
        var collection = new ShaderVariantCollection();
        var folders = new string[]{"Assets/Shaders"};
        var shaders = AssetDatabase.FindAssets("t:Shader", folders);
        foreach (var guid in shaders)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var shader = AssetDatabase.LoadAssetAtPath<Shader>(path);
            var variant = new ShaderVariantCollection.ShaderVariant(shader, PassType.ForwardAdd, "DIRECTIONAL", "SHADOWS_OFF");
            collection.Add(variant);
        }
        AssetDatabase.CreateAsset(collection, "Assets/AutoGenerated.shadervariants");
    }
}
